version: '3.8'

services:
  landing:
    build:
      context: .
    ports:
      - 8000:8000
    networks:
      - web
    command: npm run start
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.rule=Host(`dashboard.coremenus.com`)
      - traefik.http.services.api.loadbalancer.server.port=8000
      - traefik.http.routers.api.tls.certresolver=staging
      - traefik.docker.network=traefik_default

networks:
  web:
    external:
      name: traefik_default
